Update release branch
Automated updates made by [assets-release](https://github.com/sravanthi6m/azureml-assets/actions/runs/14207217460)

diff --git a/latest/component/convert_model_to_mlflow/components/convert_model_to_mlflow/spec.yaml b/latest/component/convert_model_to_mlflow/components/convert_model_to_mlflow/spec.yaml
--- a/latest/component/convert_model_to_mlflow/components/convert_model_to_mlflow/spec.yaml
+++ b/latest/component/convert_model_to_mlflow/components/convert_model_to_mlflow/spec.yaml
@@ -1,7 +1,7 @@
 $schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
 
 name: convert_model_to_mlflow
-version: 0.0.15
+version: 0.0.37
 type: command
 
 is_deterministic: true
@@ -10,28 +10,18 @@ display_name: Convert models to MLflow
 description: Component converts models from supported frameworks to MLflow model packaging
   format
 
-environment: azureml://registries/azureml/environments/model-management/versions/13
+environment: azureml://registries/azureml/environments/model-management/versions/41
 
 code: ../../src/
-command: >
-  python run_model_preprocess.py
-  $[[--model-id ${{inputs.model_id}}]]
-  $[[--task-name ${{inputs.task_name}}]]
-  $[[--model-download-metadata ${{inputs.model_download_metadata}}]]
-  $[[--license-file-path ${{inputs.license_file_path}}]]
-  $[[--hf-config-args "${{inputs.hf_config_args}}"]]
-  $[[--hf-tokenizer-args "${{inputs.hf_tokenizer_args}}"]]
-  $[[--hf-model-args "${{inputs.hf_model_args}}"]]
-  $[[--hf-pipeline-args "${{inputs.hf_pipeline_args}}"]]
-  $[[--hf-config-class ${{inputs.hf_config_class}}]]
-  $[[--hf-model-class ${{inputs.hf_model_class}}]]
-  $[[--hf-tokenizer-class ${{inputs.hf_tokenizer_class}}]]
-  $[[--hf-use-experimental-features ${{inputs.hf_use_experimental_features}}]]
-  $[[--extra-pip-requirements "${{inputs.extra_pip_requirements}}"]]
-  --model-framework ${{inputs.model_framework}}
-  --model-path ${{inputs.model_path}}
-  --mlflow-model-output-dir ${{outputs.mlflow_model_folder}}
-  --model-import-job-path ${{outputs.model_import_job_path}}
+command: |
+  # TODO: This has one disadvantage as shell logs wont be pushed to appinsights
+  set -ex
+  IFS=',' read -ra pip_pkgs <<< "$[[${{inputs.extra_pip_requirements}}]]"
+  pip_pkg_str="${pip_pkgs[*]}"
+  if [[ -n "$pip_pkg_str" ]]; then echo "Installing $pip_pkg_str"; pip install $pip_pkg_str; echo "pip installation completed. For any installation error please check above logs"; fi;
+  echo "Running model conversion ... "
+  python -u run_model_preprocess.py $[[--model-id ${{inputs.model_id}}]] $[[--task-name ${{inputs.task_name}}]] $[[--model-download-metadata ${{inputs.model_download_metadata}}]] $[[--license-file-path ${{inputs.license_file_path}}]] $[[--hf-config-args "${{inputs.hf_config_args}}"]] $[[--hf-tokenizer-args "${{inputs.hf_tokenizer_args}}"]] $[[--hf-model-args "${{inputs.hf_model_args}}"]] $[[--hf-pipeline-args "${{inputs.hf_pipeline_args}}"]] $[[--hf-config-class ${{inputs.hf_config_class}}]] $[[--hf-model-class ${{inputs.hf_model_class}}]] $[[--hf-tokenizer-class ${{inputs.hf_tokenizer_class}}]] $[[--hf-use-experimental-features ${{inputs.hf_use_experimental_features}}]] $[[--extra-pip-requirements "${{inputs.extra_pip_requirements}}"]] $[[--inference-base-image "${{inputs.inference_base_image}}"]] --vllm-enabled ${{inputs.vllm_enabled}} --model-framework ${{inputs.model_framework}} $[[--model-path "${{inputs.model_path}}"]] $[[--model-path-mmd "${{inputs.model_path_mmd}}"]] --mlflow-model-output-dir ${{outputs.mlflow_model_folder}} --model-flavor ${{inputs.model_flavor}}
+  echo "Completed model conversion ... "
 
 inputs:
   model_id:
@@ -41,12 +31,28 @@ inputs:
       in model_download_metadata JSON file.
     optional: true
 
+  model_flavor:
+    type: string
+    enum:
+    - HFTransformersV2
+    - OSS
+    default: HFTransformersV2
+    optional: false
+    description: Flavor of MLFlow to which the model is converted to.
+
+  vllm_enabled:
+    type: boolean
+    description: Enable vllm in the converted model
+    default: false
+    optional: false
+
   model_framework:
     type: string
     enum:
     - Huggingface
     - MMLab
     - llava
+    - AutoML
     default: Huggingface
     optional: false
     description: Framework from which model is imported from.
@@ -54,21 +60,30 @@ inputs:
   task_name:
     type: string
     enum:
-    - text-classification
+    - chat-completion
     - fill-mask
     - token-classification
     - question-answering
     - summarization
     - text-generation
+    - text2text-generation
     - text-classification
     - translation
     - image-classification
+    - image-classification-multilabel
     - image-object-detection
     - image-instance-segmentation
+    - image-to-text
     - text-to-image
     - text-to-image-inpainting
     - image-text-to-text
+    - image-to-image
     - zero-shot-image-classification
+    - mask-generation
+    - video-multi-object-tracking
+    - visual-question-answering
+    - image-feature-extraction
+    - feature-extraction
     description: A Hugging face task on which model was trained on. A required parameter
       for transformers MLflow flavor. Can be provided as input here or in model_download_metadata
       JSON file.
@@ -135,6 +150,13 @@ inputs:
       eg: pkg1==1.0, pkg2, pkg3==1.0
     optional: true
 
+  inference_base_image:
+    type: string
+    description: |
+      The docker image to use in model inference.
+      This image id is assigned to `azureml.base_image` key in metadata section of mlmodel file.
+    optional: true
+
   model_download_metadata:
     type: uri_file
     optional: true
@@ -144,7 +166,13 @@ inputs:
     type: uri_folder
     description: Path to the model.
     mode: ro_mount
-    optional: false
+    optional: true
+
+  model_path_mmd:
+    type: uri_folder
+    description: Path to the MMD model.
+    mode: ro_mount
+    optional: true
 
   license_file_path:
     type: uri_file
@@ -156,10 +184,6 @@ outputs:
     type: mlflow_model
     description: Output path for the converted MLflow model.
     mode: rw_mount
-
-  model_import_job_path:
-    type: uri_file
-    description: JSON file containing model job path for model lineage
 
 tags:
   Preview: ""
